Traceback (most recent call last):
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/davidcho/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Bondh5 = pd.HDFStore("data/BondDF.h5", mode="r")
BondList = Bondh5["BondList"]
BondQuant = Bondh5["BondQuant"]
BondPrice = Bondh5["BondPrice"]
Bondh5.close()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/pandas/compat/_optional.py:135[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    134[0m [38;5;28;01mtry[39;00m:
[0;32m--> 135[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[1;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90[0m, in [0;36mimport_module[0;34m(name, package)[0m
[1;32m     89[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[0;32m---> 90[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [0;32m<frozen importlib._bootstrap>:1387[0m, in [0;36m_gcd_import[0;34m(name, package, level)[0m

File [0;32m<frozen importlib._bootstrap>:1360[0m, in [0;36m_find_and_load[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:1324[0m, in [0;36m_find_and_load_unlocked[0;34m(name, import_)[0m

[0;31mModuleNotFoundError[0m: No module named 'tables'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m Bondh5 [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mHDFStore[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mdata/BondDF.h5[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m BondList [38;5;241m=[39m Bondh5[[38;5;124m"[39m[38;5;124mBondList[39m[38;5;124m"[39m]
[1;32m      3[0m BondQuant [38;5;241m=[39m Bondh5[[38;5;124m"[39m[38;5;124mBondQuant[39m[38;5;124m"[39m]

File [0;32m~/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/pandas/io/pytables.py:566[0m, in [0;36mHDFStore.__init__[0;34m(self, path, mode, complevel, complib, fletcher32, **kwargs)[0m
[1;32m    563[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mformat[39m[38;5;124m"[39m [38;5;129;01min[39;00m kwargs:
[1;32m    564[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mformat is not a defined argument for HDFStore[39m[38;5;124m"[39m)
[0;32m--> 566[0m tables [38;5;241m=[39m [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mtables[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m    568[0m [38;5;28;01mif[39;00m complib [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m complib [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m tables[38;5;241m.[39mfilters[38;5;241m.[39mall_complibs:
[1;32m    569[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    570[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mcomplib only supports [39m[38;5;132;01m{[39;00mtables[38;5;241m.[39mfilters[38;5;241m.[39mall_complibs[38;5;132;01m}[39;00m[38;5;124m compression.[39m[38;5;124m"[39m
[1;32m    571[0m     )

File [0;32m~/Documents/python_scripts/bond_analysis/lib/python3.12/site-packages/pandas/compat/_optional.py:138[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m    137[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[0;32m--> 138[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[1;32m    139[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    141[0m [38;5;66;03m# Handle submodules: if we have submodule, grab parent module from sys.modules[39;00m

[0;31mImportError[0m: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

