Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as mticker
import matplotlib.ticker as ticker
import matplotlib.dates as mdates

# Close all plots 
plt.clf()

# reformat dataframe for easier concatenation 
copy_sixteen_mil = sixteen_mil_quant
# print(copy_sixteen_mil)
copy_sixteen_mil = copy_sixteen_mil.set_index("Timestamp") 

copy_treasure_notes = treasury_notes_combined
copy_treasure_notes = copy_treasure_notes.set_index("Timestamp") 

copy_six_percent_1812 = six_percent_1812_quant
#copy_six_percent_1812 = six_percent_loans_1814_quant
copy_six_percent_1812 = copy_six_percent_1812.set_index("Timestamp") 

combined = pd.concat([copy_sixteen_mil, copy_treasure_notes, copy_six_percent_1812, others_combined.copy()], axis=1)
combined.columns.values[0] = "Sixteen Million Loan 1813"
combined.columns.values[1] = "Treasury Notes"
combined.columns.values[2] = "Six Percent Loan 1812"
combined.columns.values[3] = "Other Long-Term Bonds"

# combined["sum"] = combined["Sixteen Million Loan 1813"] + combined["Treasury Notes"] + combined["Six Percent Loan 1812"] + combined["Other Long-Term Bonds"]
# print(combined.to_string())
combined = combined.reset_index()

years = combined.index.tolist()
# Set the Seaborn style
sns.set(style="darkgrid")

# Plotting
f_plot = combined.plot(x="Timestamp", kind='area', stacked=True, figsize=(8, 6), legend=False, color=["#fd7f6f", "#7eb0d5", "#b2e061", "#bd7ebe"])

# set x axis tick marks manually
years = pd.date_range(start='1812', end='1839', freq='2YE').year
plt.xticks(pd.to_datetime(years, format='%Y'))
ax = plt.gca()
labels = ['1812', '1814', '1816', '1818', '1820', '1822', '1824', '1826', '1828', '1830', '1832', '1834', '1836', '1838'] 
ax.set_xticklabels(labels)

# set monthly locator
f_plot.yaxis.set_major_formatter(FuncFormatter(lambda x, _: '{:.1f}'.format(x / 1e6))) # Removes '1e6' from axis 
# print(combined["Other Long-Term Bonds"].max())
# f_plot.yaxis.set_ticks(np.arange(0, 7, 5e5)) 

# Adding labels and title
plt.xlabel('Year')
plt.ylabel('Total Outstanding (million)')
plt.title('Total Outstanding Over Time by Debt Type')
plt.legend(loc='upper right')

# Display the plot
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/_libs/tslibs/offsets.pyx:3878[0m, in [0;36mpandas._libs.tslibs.offsets._get_offset[0;34m()[0m

[0;31mKeyError[0m: 'YE'

The above exception was the direct cause of the following exception:

[0;31mValueError[0m                                Traceback (most recent call last)
File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/_libs/tslibs/offsets.pyx:3979[0m, in [0;36mpandas._libs.tslibs.offsets.to_offset[0;34m()[0m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/_libs/tslibs/offsets.pyx:3884[0m, in [0;36mpandas._libs.tslibs.offsets._get_offset[0;34m()[0m

[0;31mValueError[0m: Invalid frequency: YE

The above exception was the direct cause of the following exception:

[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[27], line 40[0m
[1;32m     37[0m f_plot [38;5;241m=[39m combined[38;5;241m.[39mplot(x[38;5;241m=[39m[38;5;124m"[39m[38;5;124mTimestamp[39m[38;5;124m"[39m, kind[38;5;241m=[39m[38;5;124m'[39m[38;5;124marea[39m[38;5;124m'[39m, stacked[38;5;241m=[39m[38;5;28;01mTrue[39;00m, figsize[38;5;241m=[39m([38;5;241m8[39m, [38;5;241m6[39m), legend[38;5;241m=[39m[38;5;28;01mFalse[39;00m, color[38;5;241m=[39m[[38;5;124m"[39m[38;5;124m#fd7f6f[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m#7eb0d5[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m#b2e061[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m#bd7ebe[39m[38;5;124m"[39m])
[1;32m     39[0m [38;5;66;03m# set x axis tick marks manually[39;00m
[0;32m---> 40[0m years [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mdate_range[49m[43m([49m[43mstart[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m1812[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mend[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m1839[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mfreq[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m2YE[39;49m[38;5;124;43m'[39;49m[43m)[49m[38;5;241m.[39myear
[1;32m     41[0m plt[38;5;241m.[39mxticks(pd[38;5;241m.[39mto_datetime(years, [38;5;28mformat[39m[38;5;241m=[39m[38;5;124m'[39m[38;5;124m%[39m[38;5;124mY[39m[38;5;124m'[39m))
[1;32m     42[0m ax [38;5;241m=[39m plt[38;5;241m.[39mgca()

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py:1125[0m, in [0;36mdate_range[0;34m(start, end, periods, freq, tz, normalize, name, closed, inclusive, **kwargs)[0m
[1;32m   1122[0m [38;5;28;01mif[39;00m freq [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m com[38;5;241m.[39many_none(periods, start, end):
[1;32m   1123[0m     freq [38;5;241m=[39m [38;5;124m"[39m[38;5;124mD[39m[38;5;124m"[39m
[0;32m-> 1125[0m dtarr [38;5;241m=[39m [43mDatetimeArray[49m[38;5;241;43m.[39;49m[43m_generate_range[49m[43m([49m
[1;32m   1126[0m [43m    [49m[43mstart[49m[38;5;241;43m=[39;49m[43mstart[49m[43m,[49m
[1;32m   1127[0m [43m    [49m[43mend[49m[38;5;241;43m=[39;49m[43mend[49m[43m,[49m
[1;32m   1128[0m [43m    [49m[43mperiods[49m[38;5;241;43m=[39;49m[43mperiods[49m[43m,[49m
[1;32m   1129[0m [43m    [49m[43mfreq[49m[38;5;241;43m=[39;49m[43mfreq[49m[43m,[49m
[1;32m   1130[0m [43m    [49m[43mtz[49m[38;5;241;43m=[39;49m[43mtz[49m[43m,[49m
[1;32m   1131[0m [43m    [49m[43mnormalize[49m[38;5;241;43m=[39;49m[43mnormalize[49m[43m,[49m
[1;32m   1132[0m [43m    [49m[43minclusive[49m[38;5;241;43m=[39;49m[43minclusive[49m[43m,[49m
[1;32m   1133[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m   1134[0m [43m[49m[43m)[49m
[1;32m   1135[0m [38;5;28;01mreturn[39;00m DatetimeIndex[38;5;241m.[39m_simple_new(dtarr, name[38;5;241m=[39mname)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/arrays/datetimes.py:358[0m, in [0;36mDatetimeArray._generate_range[0;34m(cls, start, end, periods, freq, tz, normalize, ambiguous, nonexistent, inclusive)[0m
[1;32m    353[0m [38;5;28;01mif[39;00m com[38;5;241m.[39mcount_not_none(start, end, periods, freq) [38;5;241m!=[39m [38;5;241m3[39m:
[1;32m    354[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    355[0m         [38;5;124m"[39m[38;5;124mOf the four parameters: start, end, periods, [39m[38;5;124m"[39m
[1;32m    356[0m         [38;5;124m"[39m[38;5;124mand freq, exactly three must be specified[39m[38;5;124m"[39m
[1;32m    357[0m     )
[0;32m--> 358[0m freq [38;5;241m=[39m [43mto_offset[49m[43m([49m[43mfreq[49m[43m)[49m
[1;32m    360[0m [38;5;28;01mif[39;00m start [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    361[0m     start [38;5;241m=[39m Timestamp(start)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/_libs/tslibs/offsets.pyx:3891[0m, in [0;36mpandas._libs.tslibs.offsets.to_offset[0;34m()[0m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/_libs/tslibs/offsets.pyx:3987[0m, in [0;36mpandas._libs.tslibs.offsets.to_offset[0;34m()[0m

[0;31mValueError[0m: Invalid frequency: 2YE

